fix: styles, naming for components, use keyframes from styled-component
KalashnikovTV/toast-lib pull request #1
Opened 2021-12-25 13:02 UTC by KalashnikovTV

Пофиксил замечания

2021-12-27 19:55 UTC, AnDrOlEiN requested changes
Way better that is was initially. Nice job

2021-12-27 19:55 UTC, AnDrOlEiN commented on src/components/ToastList/ToastList.jsx
> +    if (e.target.nodeName === 'SPAN') {
Are you sure that there’s no better way to implement such logic!

2021-12-28 12:05 UTC, KalashnikovTV commented on src/components/ToastList/ToastList.jsx
> +    if (e.target.nodeName === 'SPAN') {
I don’t know other ways, only if we check through **id**
![image](https://user-images.githubusercontent.com/58827564/147564557-7aabda8e-edac-4644-9432-5161315ae839.png)

2021-12-30 19:06 UTC, AnDrOlEiN approved these changes

2021-12-30 19:43 UTC, merged